### PR TITLE
Added play, pause, previous track, next track actions

### PR DESCRIPTION
**Pull request by giftimie**
Added some basic actions to control the player, shown when no query is made.

This is quite literally my first time working with C#. I come from a Java and NodeJS background, so it was not too hard to get used to the language but please let me know any suggestions. Depending on my spare time I may contribute to this repo every now and then, so I'd like to add as much value as possible :)

### CODE REVIEW

**Comment by waaverecords** [comment]
You beat me to it. I was gonna work on adding this this weekend.
Great contribution. I'll test it tomorrow.

Thanks @giftimie!

**Comment by waaverecords** [comment]
One thing. Can you also update the docs?

**Comment by giftimie** [comment]
Oops, missed that part. Documentation updated

**Comment by waaverecords** [comment]
Thanks!

**Comment by daerup** [comment]
Would it be able to add controls for shuffle and repeat?

**Pull request merged**
