### PR TITLE
Add zh_CN translation

### PR DESCRIPTION
**Pull request by xiaozhangup**
Sorry, I didn’t quite see where exactly to add the language name. So I created a file like this and uploaded it.

### CODE REVIEW

**Comment by waaverecords** [comment]
Sorry, I didn't see your commit was based on the localization branch.

**Comment by waaverecords** [comment]
I'll add the file manually.

**Comment by waaverecords** [comment]
The file is on the master branch.

By running `BuildAndInstallPlugin.bat`, it should build and install the plugin.

Can you test it please?

Also, if you want to be added to the list of contributors, you can submit an 'empty' PR (add a new line somewhere in the .resx file).

Thank you for the translations !

**Comment by xiaozhangup** [comment]
> The file is on the master branch.
> 
> By running `BuildAndInstallPlugin.bat`, it should build and install the plugin.
> 
> Can you test it please?
> 
> Also, if you want to be added to the list of contributors, you can submit an 'empty' PR (add a new line somewhere in the .resx file).
> 
> Thank you for the translations !


image
image
👍

**Pull request closed without merging**
